name: 自动构建发布

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - 'LICENSE'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 获取版本信息
        id: version
        run: |
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          COMMIT_DATE=$(git log -1 --format=%cd --date=format:'%Y%m%d-%H%M%S')
          VERSION="${COMMIT_DATE}-${COMMIT_SHORT}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit_short=$COMMIT_SHORT" >> $GITHUB_OUTPUT
          echo "构建版本: $VERSION"
      
      - name: 安装依赖
        run: npm install
      
      - name: 运行构建
        run: npm run build
      
      - name: 重命名发布文件
        run: |
          mv postman-web-i18n.zip postman-web-i18n-${{ steps.version.outputs.version }}.zip
      
      - name: 获取最近提交信息
        id: commit_info
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
      
      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.version.outputs.commit_short }}
          name: 构建 ${{ steps.version.outputs.version }}
          body: |
            ## 自动构建版本
            
            **版本号**: `${{ steps.version.outputs.version }}`
            **提交号**: `${{ steps.version.outputs.commit_short }}`
            **提交者**: ${{ steps.commit_info.outputs.author }}
            **提交时间**: ${{ github.event.head_commit.timestamp }}
            
            ### 提交信息
            ```
            ${{ steps.commit_info.outputs.message }}
            ```
            
            ### 安装方法
            
            1. 下载 `postman-web-i18n-${{ steps.version.outputs.version }}.zip`
            2. 解压文件
            3. 打开 Chrome 浏览器，进入 `chrome://extensions/`
            4. 开启"开发者模式"
            5. 点击"加载已解压的扩展程序"
            6. 选择解压后的 `dist` 目录
            
            ---
            
            此版本由 GitHub Actions 自动构建发布
          draft: false
          prerelease: false
          files: |
            postman-web-i18n-${{ steps.version.outputs.version }}.zip
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ steps.version.outputs.commit_short }}
          path: |
            dist/
            postman-web-i18n-${{ steps.version.outputs.version }}.zip
          retention-days: 90
      
      - name: 清理旧的 Release（保留最近10个）
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

