name: 代码检查

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 检查翻译文件
        run: npm run check-translations
        continue-on-error: true
      
      - name: 运行构建测试
        run: npm run build
      
      - name: 验证构建产物
        run: |
          if [ ! -d "dist" ]; then
            echo "错误: dist 目录不存在"
            exit 1
          fi
          
          if [ ! -f "dist/manifest.json" ]; then
            echo "错误: manifest.json 不存在"
            exit 1
          fi
          
          echo "构建产物验证通过"
      
      - name: 上传构建产物（用于预览）
        uses: actions/upload-artifact@v4
        with:
          name: pr-build-preview
          path: dist/
          retention-days: 7
